# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Decentralized Data Workshops
tagline:          'Level up with Distributed Systems'
description:      'Workshop material on distributed version control and distributed data systems. Created as part of the Dat Jawn project at Code for Philly'
url:              http://CfABrigadePhiladelphia.github.io/decentralized-data/
baseurl:          /decentralized-data

author:
  name:           'Matt Zumwalt'
  url:            https://twitter.com/flyingzumwalt

# Custom vars
version:          0.0.1
gems:             [jekyll-paginate, jekyll-gist]

github:
  repo:           https://github.com/CfABrigadePhiladelphia/decentralized-data
